### ISSUE TITLE
Measuring FGD on Trinity - Mismatch input size error

### ISSUE THREAD

**Issue by anithselva** [yesheng-THU/GFGE#2]
I'm having some challenges calculating metrics on Trinity dataset.

Specifically, when I run cal_metrics.py, here is the error that I get

```
Exception has occurred: RuntimeError
  input.size(-1) must be equal to input_size. Expected 1281, got 1262
  File "/home/GFGE/glow/modules.py", line 426, in forward
    gru_out, self.hidden = self.gru(input)
  File "/home/GFGE/glow/models.py", line 183, in reverse_flow
    h = self.f(z1_cond.permute(0, 2, 1)).permute(0, 2, 1)
  File "/home/GFGE/glow/models.py", line 132, in forward
    return self.reverse_flow(input, cond, logdet, feat=feat, semantic=semantic, noise=noise)
  File "/home/GFGE/glow/models.py", line 254, in forward
    z, cond, logdet = layer(z, cond, logdet=0, reverse=True, feat=feat, semantic=semantic, noise=noise)
  File "/home/GFGE/glow/models.py", line 351, in reverse_flow
    x = self.flow(z, cond, eps_std=eps_std, reverse=True, feat=feat, semantic=semantic, noise=noise)
  File "/home/GFGE/glow/models.py", line 326, in forward
    return self.reverse_flow(z, cond, eps_std, feat, semantic, noise, z_shape)
  File "/home/GFGE/scripts/cal_metrics.py", line 206, in generate_sample
    sampled = graph(z=None, cond=cond, eps_std=eps_std, reverse=True, z_shape=[nn, 27, 1])
  File "/home/GFGE/scripts/cal_metrics.py", line 243, in evaluate_testset
    out_dir_vec, target = generate_sample(generator, data, hparams, device)
  File "/home/GFGE/scripts/cal_metrics.py", line 470, in eval_FGD
    evaluate_testset(data_motion, test_data_loader, built_motion['graph'], embed_space_evaluator, hparams_motion, device)
  File "/home/GFGE/scripts/cal_metrics.py", line 489, in <module>
    eval_FGD()
```

I've downloaded the feature extractor checkpoints. Could this be a mismatch between checkpoints of the model and the feature extractor?

**Comment by yesheng-THU** [comment]
Thanks for your attention.
The current cal_metrics.py is for the TED dataset.
For measuring FGD on Trinity Dataset, you need to train a specific feature extractor for Trinity Dataset (please refer to scripts/train_gp_loss.py) and modify the hyperparameters (match the size of Trinity data) in cal_metrics.py to avoid the mismatch input size error.

**Comment by anithselva** [comment]
Hi @yesheng-THU - Would you able to advise on the any changes that need to be made to train the gp_loss feature extractor successfully?
Made some changes to match the data but still running into issues:

```
Traceback (most recent call last):
  File "scripts/train_gp_loss.py", line 181, in <module>
    x_recon = model(x, n_pose)
  File "/GFGE/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GFGE/glow/vae_model.py", line 139, in forward
    x = x.permute([0,2,1]).reshape(-1, num_frames, self.n_dim)
RuntimeError: shape '[-1, 30, 65]' is invalid for input of size 207360
```

**Comment by anithselva** [comment]
I'm noticing vae_model.py Autodecoder has some hard-coded values that are specific for TED dataset. I've made some progress, but am still stuck at training the feature extractor for the Trinity Dataset 
Hoping you could guide on the specific changes that need to be made to support Trinity dataset based feature extractor.

Thanks
